### ISSUE TITLE
Unable to decrypt a file with decrypt-file.php script

### ISSUE THREAD

**Issue by AugustMacke** [syseleven/nextcloud-tools#6] opened 2020-11-29 13:12 UTC
I've set up a test server with a Nextcloud 20.0.1 (upgraded from 18 to 19 to 20) installation. In the admin settings, I enabled the server side encryption with encryption of the home storage. Now I try to manually decrypt a file with the decrypt-file.php script.

In the script I filled the variables DATADIRECTORY, INSTANCEID and SECRET with a proper value. I guess that I have the KEY_MASTER keytype, as I didn't change anything else in the encryption configuration.

When I execute the script, the decryption of my test file fails. I added some logging to better understand what happens. The issue seems to be that the private key is not decrypted. As far as I understood the script, the splitMetaData function seems to not do its job correctly.

The log output is:
florian@florians-ubuntu-server:~/decrypt-nextcloud$ php ./decrypt-file.php admin/files/Encryption/geheim.md
##################################################
$filename = '/home/florian/decrypt-nextcloud/data/admin/files/Encryption/geheim.md'
$filekeyfilename in handleFile = '/home/florian/decrypt-nextcloud/data/admin/files_encryption/keys/files/Encryption/geheim.md/OC_DEFAULT_MODULE/fileKey'
$sharekeyfilename in handleFile = '/home/florian/decrypt-nextcloud/data/admin/files_encryption/keys/files/Encryption/geheim.md/OC_DEFAULT_MODULE/master_b802b2b6.shareKey'
$keyid = 'master_b802b2b6'
$header in decryptPrivateKey = array (
)
$meta in hasSignature = '21570ee70cacc4151f05f462270e3c7713c425cadb0a926433e5eb18d577e53578568d50bb1d3b0471801c7a1ba|2'
$pos in hasSignature = false
File does not have a signature
$meta in decryptPrivateKey = array (
  'encrypted' => false,
  'iv' => '',
  'signature' => false,
)
$keyModified = false
PHP Warning:  openssl_open(): unable to coerce parameter 4 into a private key in /home/florian/decrypt-nextcloud/decrypt-file.php on line 406
/home/florian/decrypt-nextcloud/data/admin/files/Encryption/geheim.md: File not decrypted.
##################################################

The PHP Warning happens in line 391 in the original file.

You can see that the file $header is empty and the $meta variable contains wrong information. When I have a look into my file, there IS an iv and the file is encrypted and there is a signature (as far as I understood the content of the file).

The encrypted test file is attached. I added .txt at the end to be able to upload it.
[geheim.md.txt](https://github.com/syseleven/nextcloud-tools/files/5612198/geheim.md.txt)

Thank you in advance to have a look at it!

Best regards,
Florian

**Comment by yahesh** [comment] 2020-11-29 13:24
That's actually a known problem. Nextcloud 20 introduced an additional encryption layer for the key material. The decrypt-all-files.php script already supports this new format while I haven't yet come around to updating the decrypt-file.php script accordingly.

**Comment by AugustMacke** [comment] 2020-11-29 19:38
Ah, okay, so I use the decrypt-all-files.php and this basically seems to work.
My problem goes a bit further, as my "productive" nextcloud messed up with the encryption and is unable to access most of the files. So I try to decrypt them with this script. The output of the decrypt-all-files.php is:

ERROR: .../Photos/Steps.jpg FAILED
PHP Warning:  hex2bin(): Input string must be hexadecimal string in /.../decrypt-all-files.php on line 127
PHP Warning:  openssl_decrypt(): IV passed is only 3 bytes long, cipher expects an IV of precisely 16 bytes, padding with \0 in /.../decrypt-all-files.php on line 138

In the editor the IV for that file looks like that: 00iv00\88)\FFE\F4\86\A2;4\C5\C9O\8A\9D\D700sig00 which seems a bit strange to me.

The IV length varies for every file. Sometimes its longer, sometimes shorter than the expected 16 bytes. Any guess why Nextcloud messed up the IV? Can this be any issue regarding to the encoding?

**Comment by yahesh** [comment] 2020-11-29 20:02
@AugustMacke I think that the warnings do not have something to do with your actual problem. The warnings stem from the `decrypt-all-files.php` trying to be smart, but in the case of this specific file this rather leads to a warning. I updated the script so that it should not throw these warnings anymore. However, I guess that your specific problem will still persist.

**Comment by yahesh** [comment] 2020-12-02 07:39
@AugustMacke Did you have any progress with the updated `decrypt-all-files.php` script?

**Comment by AugustMacke** [comment] 2020-12-06 12:31
@yahesh You are right, the problem seems not to be related to the IV. I ran the newest version of the `decrypt-all-files.php` and the output no longer appears. But never the less I am not able to decrypt the files.
I could locate the problem in line 465 (in decryptFile -> openssl_open) which returns nothing. But I can see that all parameters are set. I have a fileKey, a shareKey, a keyname, a privateKey for the keyname, a fileName and a target. So my problem seems to be that something does not fit together, but I can't find out what.

**Comment by yahesh** [comment] 2020-12-06 13:44
@AugustMacke Are these productive data or does the same happen for you with test data? What I can offer is that you can provide me with a data set (instance-id, secret, filekey, sharekye, private key, (optionally) user/recovery password and the actual encrypted file) and I can have a manual look to see what might be wrong. If you're willing to do that you can find my e-mail address in my profile.

**Comment by AugustMacke** [comment] 2020-12-06 15:02
This is an issue related to my "productive" server (sharing photos with friends). On my test server I could not reproduce it. I think this has happened by updating Nextcloud to Version 20, but it's only occuring in special circumstances. I'm watching an [issue of Nextcloud](https://github.com/nextcloud/server/issues/23197) which looks pretty much like my problem.
It's not that important to me to get the files decrypted, as they all should still exist somwhere, so thank you but I won't take your offer.
Thank you very much for helping me here with this script, but I think that Nextcloud should fix this problem. It's not an issue of the script.

**Comment by yahesh** [comment] 2020-12-06 16:26
@AugustMacke Ok. Sorry, that I cannot help at the moment. `openssl_open()` is a combined RSA-PKCS1.5 decryption of the sharekey with the corresponding private key of the recipient, followed by an RC4 decryption of the filekey with the decrypted sharekey. If the error happens at this stage that at least means that the private key could properly be decrypted and that the error happens directly between the decryption of the private key key and the decryption of the actual file.

So, in order to reproduce the problem one wouldn't need an actual encrypted file.

**Comment by yahesh** [comment] 2020-12-08 11:48
I had another look at the decrypt-all-files.php and was able to locate 2 bugs, one for files that only contain the encryption header but no data and one for files that have been changed after an update to Nextcloud 20. Maybe these changes yield a better decryption result for you as well.

**Comment by if0xx** [comment] 2021-01-21 21:53
Hi, could you please update decrypt-file.php for NC 20?

Currently this is the **only** way for me to access files that the web UI can't show due to this issue:  #23197

I CAN successfully use decrypt-file.php after replacing the master key file with a backup version stored under NC19, so my files / keys are basically all there. But NC 20 immediately overwrites this key file with the NC20 version which doesn't work with decrypt-file.php.

Also, could you please reopen the issue mentioned above? It is NOT solved in 20.0.5.

**Comment by Eeems** [comment] 2021-01-21 21:55
> Currently this is the **only** way for me to access files that the web UI can't show due to this issue: #23197

Did you mean https://github.com/nextcloud/server/issues/23197?

**Comment by if0xx** [comment] 2021-01-21 22:00
Yes, sorry for the broken link!

**Comment by yahesh** [comment] 2021-01-21 22:22
@if0xx Hi, in that Nextcloud issue you mentioned that _"decrypt-all-files.php is no help either as it silently fails to decrypt ALL files."_ Could please give some more information where it fails silently?

**Comment by if0xx** [comment] 2021-01-21 23:02
@yahesh sure: decrypt-all-files.php replicates the whole file tree from the data directory in the target directory, but all files are 0 bytes in size.

Also, occ encryption:decrypt-all didn't help, it gave an error for every single file and didn't seem to touch files at all.

That said, all files (as far as I tried) can be decrypted correctly using decrypt-file.php and the master key file from NC19.

IMHO the cleanest approach would be to 

1. make sure the server can read all files (a.k.a. Web UI & DAV/sync clients working)
2. fix occ encryption:decrypt-all so admins can actually get rid of OC_DEFAULT encryption

**Comment by yahesh** [comment] 2021-01-21 23:23
@if0xx Did you try the `decrypt-all-files.php` with your backed-up NC19 master key file as well? Did it yield the same result as with the NC20 master key file? Did you have a look at the result code of the call to the `decrypt-all-files.php` script (e.g. via `echo $?`)? My assumption is that the script fails within a codepath that would be transferred to an updated version of the `decrypt-file.php` script, so updating that script won't help unless the problem that leads to the empty files is fixed before.

**Comment by yahesh** [comment] 2021-01-21 23:58
@if0xx I created a debug version with some initial debugging messages. Maybe you could give it a turn: https://gist.github.com/yahesh/250a4e3d985fe847652232f2c27dfc38

**Comment by AugustMacke** [comment] 2021-01-31 16:53
@if0xx Where do I find the old NC 19 key? I'm using the snap so the update happened automatically for me. I hope it is still anywhere. Otherwise it would be a very nice migration process from the Nextcloud updater to first delete the keys and then try to migrate the files...

**Comment by yahesh** [comment] 2021-05-31 11:36
@AugustMacke Is this still a problem or has this resolved in the meantime?

**Comment by AugustMacke** [comment] 2021-06-12 11:02
There are still encrypted files in my Nextcloud which cannot be decrypted. I saw that you updated the script, so I gave it another run. But the result is the same. Here is the log:

DEBUG: debug mode enabled
DEBUG: loaded private key for master_e5316375
DEBUG: loaded private key for pubShare_e5316375
...
DEBUG: filename = /home/florian/cloud/data/august/files/Willkommen/_Willkommen.md
DEBUG: datafilename = Willkommen/_Willkommen.md
DEBUG: istrashbin = false
DEBUG: username = august
DEBUG: filekey = /home/florian/cloud/data/august/files_encryption/keys/files/Willkommen/_Willkommen.md/OC_DEFAULT_MODULE/fileKey
DEBUG: isencrypted = true
DEBUG: sharekey = /home/florian/cloud/data/august/files_encryption/keys/files/Willkommen/_Willkommen.md/OC_DEFAULT_MODULE/master_e5316375.shareKey
DEBUG: secretkey = unavailable
DEBUG: skipping this file...
DEBUG: success = false
...
DEBUG: filename = /home/florian/cloud/data/files_encryption/OC_DEFAULT_MODULE/master_e5316375.privateKey
DEBUG: filename = /home/florian/cloud/data/files_encryption/OC_DEFAULT_MODULE/master_e5316375.publicKey
DEBUG: filename = /home/florian/cloud/data/files_encryption/OC_DEFAULT_MODULE/pubShare_e5316375.privateKey
DEBUG: filename = /home/florian/cloud/data/files_encryption/OC_DEFAULT_MODULE/pubShare_e5316375.publicKey

Is the unavailable secretkey the problem? What could be the reason for that? I have set datadirectory, instanceid and secret in the script.

**Comment by yahesh** [comment] 2021-06-12 11:46
@AugustMacke I found an issue when the first sharkey does not match, I also added more debug messages so that one see why the secretkey is unavailable. You could have another try.

**Comment by AugustMacke** [comment] 2021-06-13 15:05
@yahesh Here the new run.
Is it possible that I have the same issue as @if0xx had? The problem for me is, that I don't have any backup master file key because snap updated NC automatically.

DEBUG: filename = /home/florian/cloud/data/august/files/Willkommen/_Willkommen.md
DEBUG: datafilename = Willkommen/_Willkommen.md
DEBUG: istrashbin = false
DEBUG: username = august
DEBUG: filekeyname = /home/florian/cloud/data/august/files_encryption/keys/files/Willkommen/_Willkommen.md/OC_DEFAULT_MODULE/fileKey
DEBUG: isencrypted = true
DEBUG: sharekeyname = /home/florian/cloud/data/august/files_encryption/keys/files/Willkommen/_Willkommen.md/OC_DEFAULT_MODULE/master_e5316375.shareKey
DEBUG: secretkey could not be decrypted
DEBUG: secretkey = unavailable
DEBUG: skipping this file...
DEBUG: success = false
ERROR: /home/florian/cloud/data/august/files/Willkommen/_Willkommen.md FAILED

**Comment by yahesh** [comment] 2021-06-13 16:17
@AugustMacke It looks somewhat strange. `loaded private key for master_e5316375` means that the private key could be decrypted properly and should be available for the decryption of the secret key. As the script tries to decrypt the secretkey is also means that it presumably could read the filekey and the sharekey from disk.

There are two things that one could do next:

1.) Have a look whether `/home/florian/cloud/data/august/files_encryption/keys/files/Willkommen/_Willkommen.md/OC_DEFAULT_MODULE/fileKey` is actually non-empty and has the proper structure.
2.) Have a look whehther `/home/florian/cloud/data/august/files_encryption/keys/files/Willkommen/_Willkommen.md/OC_DEFAULT_MODULE/master_e5316375.shareKey` is actually non-empty and has the proper structure.

Another alternative would be to provide all the relevant files and configuration so that I can manually step through the decryption process. But that would only be the last option.

**Comment by AugustMacke** [comment] 2021-06-24 18:11
@yahesh Both files are not empty. But I don't know how to recognize a proper structure

**Comment by acsfer** [comment] 2021-08-20 08:38
We're having a similar probel with one of our files, here is the debug strace:

```
# php -f decrypt-all-files.php /tmp/decrypted "file.docx"
DEBUG: debug mode enabled
DEBUG: loaded private key for master_f303f01d
DEBUG: loaded private key for pubShare_f303f01d
DEBUG: filename = file.docx
DEBUG: target = /tmp/decrypted/file.docx
DEBUG: datafilename = file.docx
DEBUG: istrashbin = false
DEBUG: username = user
DEBUG: secretkey = unavailable
DEBUG: trying to copy file...
DEBUG: success = false
ERROR: file.docx FAILED
DEBUG: exiting
```
Both `filekey` and `master_f303f01d` are non-empty (here attached).

[OC_DEFAULT_MODULE.zip](https://github.com/syseleven/nextcloud-tools/files/7020242/OC_DEFAULT_MODULE.zip)

**Comment by yahesh** [comment] 2021-08-20 12:58
@acsfer I'd expect there to be debug log entries in the form:
```
filekeyname = $DATADIRECTORY/user/files_encryption/keys/files/file.docx/OC_DEFAULT_MODULE/fileKey
isencrypted = true
sharekeyname = $DATADIRECTORY/user/files_encryption/keys/files/file.docx/OC_DEFAULT_MODULE/master_f303f01d.shareKey
```

However, these are missing in your provided logs. Could you provide the **full** path of the `fileKey` file as well as the corresponding `master_f303f01d.shareKey` file? Looking at your files you have not yet updated to the new encryption scheme, maybe you are using an encryption scheme that is older than Nextcloud 16, so that the files may be located somewhere different and thus aren't found.

**Comment by acsfer** [comment] 2021-08-20 13:08
Sure:

```
# php -f decrypt-all-files.php /tmp/decrypted "GroupServiceTechnique/files/Partage Service Infra & Prod/02 - Support/02 - Procédures internes D2SI/PRO_D2SI_I&P_015_Moffi.docx"
DEBUG: debug mode enabled
DEBUG: loaded private key for master_f303f01d
DEBUG: loaded private key for pubShare_f303f01d
DEBUG: filename = GroupServiceTechnique/files/Partage Service Infra & Prod/02 - Support/02 - Procédures internes D2SI/PRO_D2SI_I&P_015_Moffi.docx
DEBUG: target = /tmp/decrypted/GroupServiceTechnique/files/Partage Service Infra & Prod/02 - Support/02 - Procédures internes D2SI/PRO_D2SI_I&P_015_Moffi.docx
DEBUG: datafilename = Partage Service Infra & Prod/02 - Support/02 - Procédures internes D2SI/PRO_D2SI_I&P_015_Moffi.docx
DEBUG: istrashbin = false
DEBUG: username = GroupServiceTechnique
DEBUG: secretkey = unavailable
DEBUG: trying to copy file...
DEBUG: success = false
ERROR: GroupServiceTechnique/files/Partage Service Infra & Prod/02 - Support/02 - Procédures internes D2SI/PRO_D2SI_I&P_015_Moffi.docx FAILED
DEBUG: exiting
```
Please note that other files on the same level decrypted fine.

**Comment by yahesh** [comment] 2021-08-20 13:13
@acsfer I actually meant the full paths of the `filekey` and `*.shareKey` files that you have provided, these are still missing.

If the `occ encryption:decrypt-all` has run but these files remained encrypted than it's very well possible that it's a problem with the file itself. In the case of this specific file the script isn't able to locate the `filekey` and `*.shareKey` file.

**Comment by acsfer** [comment] 2021-08-20 13:17
I understand, files aren't **located** by the script, but they are **physically** there, because of https://github.com/nextcloud/server/issues/28286

They are at `/data/GroupServiceTechnique/files_encryption/keys/files/Partage Service Technique/02 - Support/02 - Procédures internes D2SI/PRO_D2SI_I&P_015_Moffi.docx/OC_DEFAULT_MODULE` (these are the files i've attached at https://github.com/syseleven/nextcloud-tools/issues/6#issuecomment-902533469)

![image](https://user-images.githubusercontent.com/12234510/130239102-4b616e09-1733-4329-a0b4-8bde59b6eb66.png)

**Comment by yahesh** [comment] 2021-08-20 13:23
@acsfer I'm a bit at a loss here. If the file that cannot be decrypted is called `GroupServiceTechnique/files/Partage Service Infra & Prod/02 - Support/02 - Procédures internes D2SI/PRO_D2SI_I&P_015_Moffi.docx` the corresponding `fileKey` and `*.shareKey` file should be located in a folder called `GroupServiceTechnique/files_encryption/keys/files/Partage Service Infra & Prod/02 - Support/02 - Procédures internes D2SI/PRO_D2SI_I&P_015_Moffi.docx/OC_DEFAULT_MODULE/`. But in your case it seems to be called `GroupServiceTechnique/files_encryption/keys/files/Partage Service Technique/02 - Support/02 - Procédures internes D2SI/PRO_D2SI_I&P_015_Moffi.docx/OC_DEFAULT_MODULE/` (take note of `Partage Service Infra & Prod` vs. `Partage Service Technique`). These folders don't match.

**Comment by acsfer** [comment] 2021-08-20 13:32
**BINGO!** Well, i believe the Folder has been renamed since `occ encryption:decrypt-all` has been run.
Since the files are decrypted, folder under `files_encryption/keys/files/` hasn't been renamed/updated.

I've manually renamed it an file has been decrypted :)
PS: out of topic, but any idea about https://github.com/nextcloud/server/issues/28286?

**Comment by yahesh** [comment] 2021-08-20 13:43
@acsfer When looking at the corresponding function to decrypt such a file during the `occ encryption:decrypt-all` run, [it doesn't contain a step to delete the key material](https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/private/Encryption/DecryptAll.php#L252-L275). I assume the person implementing the decryption didn't want to take the risk of losing the key material in case the decryption fails for whatever reason.

**Comment by acsfer** [comment] 2021-08-20 13:46
@yahesh makes sense, I'll keep them myself for a while too to be sure that i don't need them...
Perhaps copy your answer at https://github.com/nextcloud/server/issues/28286 ;)

`(thanks for your help here 👍 !!)`

**Comment by yahesh** [comment] 2022-04-12 06:44
@AugustMacke Do you have any updates on this? Otherwise I'd close the issue in the next few weeks.

**Comment by yahesh** [comment] 2022-12-28 16:24
Will close this ticket as there hasn't been any reaction for over year now.

**Closed by yahesh** 2022-12-28 16:24 UTC
Labels: question
